### ISSUE TITLE
Fatal error: Call to private method WHMCS::api() from context ''

### ISSUE THREAD

**Issue by fiveleaf** [cmantito/whmcs-php#2]
I've attempted to use the class to make API calls (specifically inserting new leads into a CRM module developed by Modules Garden) and receive the following error:

**Fatal error: Call to private method WHMCS::api() from context ''**

I'm trying to make an external API call if that helps. I a bit of a newb when it comes to PHP Classes. I tried modifying the codes to change **private** function api($action, $params) to **public** function api($action, $params) which caused there to not be an error, but also didn't cause a successful lead posting. I'm not sure the difference between public and private and would bet this function is private for a reason anyway.

Modules Garden uses your class in their documentation for making API calls so I'm thinking it _should_ work as you have it written. I'm new to GitHub so forgive me if this is not what the issues space is for. Just hoping to get some insight.

**Comment by echoesactiii** [comment]
WHMCS::api() is private because it is a function that is intended to be used by other public functions within the class, and not meant to be exposed outside of the class. For more information about public/private functions, see http://php.net/manual/en/language.oop5.visibility.php

If you can provide me a code sample, or an example of what kind of API call you're trying to make, I can probably help you out! :smile_cat:

**Comment by fiveleaf** [comment]
So the documentation for adding a lead to the CRM module via API calls says to use:

$parameters["type"] = "potential";
$parameters["ticketid"] = "563";
$parameters["clientid"] = "31";
$parameters["addtodo"]  = "true";

$parameters["field"]["Name"]    = "Test Lead Name";
$parameters["field"]["Status"]  = "New";
$parameters["field"]["Campaign"]    = "New Promotion";
$parameters["field"]["Business Type"]   = "Small";

$whmcs      = new WHMCS("api-url", 'api-user', 'password', 'optional-access-key');
$response   = $whmcs->api("crmadditem", $parameters);

Using this (with our own api-url, api-user, and password of course and no access key), results in the error I mentioned before. I've tried with with both their _exact_ sample code and with the code I needed it to execute.

$parameters["type"]  = "lead";
$parameters["field"]["Full Name"]   = $fname.' '.$lname;
$parameters["field"]["First Name"]  = $fname;
$parameters["field"]["Last Name"]   = $lname;
$parameters["field"]["Email"] = $email;
$parameters["field"]["Status"] = "New";
$parameters["field"]["Source"] = "Website Notification Request";
$parameters["field"]["Questions or Comments"] = $questionsComments;
require_once('./includes/whmcs.class.php');
$whmcs      = new WHMCS($api_url,$admin_username,$admin_password);
$response   = $whmcs->api("crmadditem", $parameters);

This also results in the same error.

**Comment by echoesactiii** [comment]
Ahh. Yes, if you were going to use it in that way, you would need to change WHMCS::api() from private to public to make it available to the code calling it there. What happened when you tried to run those code snippets with API exposed as a public function?

Realisitically, what you'd want to do is extend the class, adding a WHMCS::crmaditem() function, e.g.:

``` php
class WhmcsCrm extends WHMCS {
    public function addCrmItem($your_required, $params_here){
        // put together your $parameters array as above in your example

        $response = $this->api('crmadditem', $parameters)

        if($response->result == 'error'){
        throw new WhmcsException("WHMCS complained: ".$response->message);
        }

        return $response;
    }
}
```

And then from within your code, you'd be able to do something like:

``` php
require_once('include/whmcs.class.php'); // my version of the class.
require_once('include/whmcscrm.class.php'); // your extended version of the class, as above.
$whmcs = new WhmcsCrm('url','username','password');
$whmcs->addCrmItem("Whatever", "parameters", "you", "defined", "above");
```

_Really_, what Modules Garden should've done was a release an extended version of this class that already has all their functions in it. That would be the correct way of handling this - but that's not your fault.

Looking at their wiki, it seems they may have provided a link to this github page in order to download the connection class? If so, then they've provided the incorrect guidance and code examples, because the ones shown in their wiki will not work with this class as-is, unless you first modify the class to make the WHMCS::api() function public...

**Comment by fiveleaf** [comment]
Thank you so much for the useful response. I will try your suggestions. Do you mind if I include your response in the trouble ticket I submitted to Modules Garden so perhaps I can save someone else some frustration and headache?

**Comment by echoesactiii** [comment]
No problem, let me know if you have any trouble.
You may certainly use my reply - I'm not a customer of theirs, but I'm quite tempted to open a ticket with them myself advising them that their instructions will not technically work with this library!

**Comment by fiveleaf** [comment]
Hmmm. Those suggestions didn't work either. I'm contacting their support channels again to see if they can clear this issue up. I'm sorry for taking up your time with this issue, and I truly appreciate your willingness to help. Thanks!

**Comment by echoesactiii** [comment]
No problem - I'd be curious to hear how you get on with it/what they say. I have no idea what the code they used to add functions to the external API looks like, so it's somewhat hard for me to imagine what's going wrong at the moment.

**Comment by eugenefvdm** [comment]
Hi,

I have a similar problem as @fiveleaf .
1. I was referred to this API from Modules Garden built-in help in WHMCS suggesting I use this API.
2. First I tried making the private function public. I get a success from the API.

Although I do get a lead in WHMCS, I don't see the additional fields.

So I'm curious to know from @fiveleaf  what happened after contacting Modules Garden support.

![whmcs crm](https://cloud.githubusercontent.com/assets/1836436/8544628/29868bee-24a7-11e5-9165-590d338d615b.png)

**Comment by eugenefvdm** [comment]
No sooner had I posted this then I found this link https://gist.github.com/picq/e5ca60cbf0de002722f9

The API documentation is wrong, you use field_ underscore to designate your fields, not the actual name of the the custom field.

$parameters["field"]["field_1"] = "Test Lead Name";
$parameters["field"]["field_2"] = "tes@tt.com";
$parameters["field"]["field_3"] = "123456789";
$parameters["field"]["field_4"] = "New";
$parameters["field"]["field_5"] = "Awesome campaign";
$parameters["field"]["field_6"] = "anonymous source";
$parameters["field"]["field_7"] = "no Industry";

**Comment by echoesactiii** [comment]
@eugenevdm That's helpful and probably the issue here. Realistically, Module Garden _really_ does need to release their own API module with a class that extends the WHMCS class, as that's the most appropriate way to do that. :/

**Comment by echoesactiii** [comment]
It seems Module Garden has their own API module that's based on this library, it might be worth looking at for anyone in the future: https://github.com/modgarden/modulesgarden-crm-api
